import React from 'react'

function BlogPage() {
    return (
        <div className='blog-page d-flex flex-column w-50 text-left document-page'>
            <h1>Blog Page</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Ipsum consequat nisl vel pretium lectus quam id leo. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Pharetra convallis posuere morbi leo urna molestie at elementum eu. At urna condimentum mattis pellentesque id nibh tortor. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Et ligula ullamcorper malesuada proin libero nunc consequat. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Eu ultrices vitae auctor eu.

                Nunc congue nisi vitae suscipit tellus. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Suscipit tellus mauris a diam. Id semper risus in hendrerit gravida rutrum quisque non tellus. Aliquet enim tortor at auctor urna nunc id cursus metus. Elementum sagittis vitae et leo duis ut diam. Sapien eget mi proin sed libero enim sed faucibus. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Porttitor lacus luctus accumsan tortor. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. At auctor urna nunc id. Imperdiet dui accumsan sit amet nulla facilisi morbi. Adipiscing elit ut aliquam purus. Massa ultricies mi quis hendrerit. Ut lectus arcu bibendum at varius vel pharetra. Facilisis mauris sit amet massa vitae tortor condimentum.

                Nunc faucibus a pellentesque sit amet porttitor. Risus nec feugiat in fermentum. Suspendisse potenti nullam ac tortor vitae purus faucibus. Sagittis nisl rhoncus mattis rhoncus urna neque. Tristique senectus et netus et. Porttitor rhoncus dolor purus non. Quisque non tellus orci ac auctor. Leo a diam sollicitudin tempor id eu nisl nunc. Dui faucibus in ornare quam viverra orci. Vel pharetra vel turpis nunc eget lorem.

                Aliquam ultrices sagittis orci a scelerisque purus semper eget. A diam sollicitudin tempor id eu nisl. Velit euismod in pellentesque massa placerat duis ultricies. In aliquam sem fringilla ut. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Nisl nisi scelerisque eu ultrices. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Accumsan tortor posuere ac ut consequat semper viverra. Gravida neque convallis a cras semper auctor neque vitae. Praesent elementum facilisis leo vel fringilla est. Volutpat sed cras ornare arcu dui vivamus arcu. Felis eget velit aliquet sagittis id consectetur purus ut.

                Volutpat commodo sed egestas egestas fringilla. Magna eget est lorem ipsum dolor. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Amet consectetur adipiscing elit duis tristique sollicitudin. Tincidunt tortor aliquam nulla facilisi cras. Sed risus ultricies tristique nulla aliquet. Est ultricies integer quis auctor elit sed. Odio pellentesque diam volutpat commodo. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Placerat duis ultricies lacus sed. Ridiculus mus mauris vitae ultricies leo integer. Tempus urna et pharetra pharetra massa massa ultricies. Viverra suspendisse potenti nullam ac tortor. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Sit amet massa vitae tortor. Lobortis feugiat vivamus at augue eget arcu dictum.

                Est placerat in egestas erat imperdiet. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Porta nibh venenatis cras sed felis. Fermentum leo vel orci porta non pulvinar neque laoreet. Fames ac turpis egestas sed tempus urna. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Sed odio morbi quis commodo. In hac habitasse platea dictumst vestibulum rhoncus est. At elementum eu facilisis sed odio morbi quis commodo odio. Hendrerit gravida rutrum quisque non tellus.

                Diam maecenas sed enim ut sem viverra aliquet. Sit amet justo donec enim diam vulputate. Tortor at risus viverra adipiscing. Semper viverra nam libero justo laoreet sit amet. Velit scelerisque in dictum non consectetur. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Nisl suscipit adipiscing bibendum est. Integer enim neque volutpat ac. Gravida neque convallis a cras semper auctor neque. Tristique senectus et netus et malesuada fames ac turpis. Mattis enim ut tellus elementum sagittis vitae et. Id aliquet lectus proin nibh. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Eu volutpat odio facilisis mauris sit.

                Eu lobortis elementum nibh tellus molestie nunc. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Nisl condimentum id venenatis a condimentum. Sed augue lacus viverra vitae congue eu consequat. Semper risus in hendrerit gravida rutrum quisque. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Quisque id diam vel quam elementum pulvinar. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Lectus quam id leo in vitae turpis massa sed elementum.

                In vitae turpis massa sed elementum tempus egestas. Convallis aenean et tortor at risus. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Nullam ac tortor vitae purus faucibus ornare suspendisse. Morbi tempus iaculis urna id. Euismod lacinia at quis risus sed vulputate. Dis parturient montes nascetur ridiculus mus mauris. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Sed cras ornare arcu dui. Condimentum mattis pellentesque id nibh tortor id. Tristique magna sit amet purus gravida quis. Sed cras ornare arcu dui vivamus arcu felis. Bibendum enim facilisis gravida neque convallis a. Viverra aliquet eget sit amet tellus cras adipiscing.

                Pellentesque nec nam aliquam sem et tortor consequat. Tortor condimentum lacinia quis vel eros. Adipiscing tristique risus nec feugiat. Egestas quis ipsum suspendisse ultrices. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Ut placerat orci nulla pellentesque. Et tortor at risus viverra. Sed euismod nisi porta lorem. Tristique sollicitudin nibh sit amet. Semper quis lectus nulla at volutpat diam. Risus nullam eget felis eget nunc lobortis. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque.

                Morbi non arcu risus quis varius quam quisque id diam. Ultricies leo integer malesuada nunc vel risus commodo. Rhoncus dolor purus non enim praesent elementum facilisis leo. Consequat semper viverra nam libero justo. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Quis vel eros donec ac odio tempor orci dapibus ultrices. Vitae suscipit tellus mauris a. Urna et pharetra pharetra massa massa ultricies mi quis. Amet volutpat consequat mauris nunc congue. Tristique nulla aliquet enim tortor at auctor urna. Morbi tristique senectus et netus et malesuada fames. Libero enim sed faucibus turpis in. Eget aliquet nibh praesent tristique magna sit amet. Cras ornare arcu dui vivamus arcu felis bibendum. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec.

                Et tortor at risus viverra adipiscing. Magna eget est lorem ipsum dolor sit amet consectetur. Tempor orci dapibus ultrices in iaculis nunc sed. Nec dui nunc mattis enim ut tellus. Enim nec dui nunc mattis enim ut tellus. Vitae congue eu consequat ac felis donec et odio pellentesque. Magna eget est lorem ipsum dolor. Mauris commodo quis imperdiet massa tincidunt nunc. Faucibus interdum posuere lorem ipsum dolor sit. Viverra vitae congue eu consequat ac. At lectus urna duis convallis convallis tellus id interdum velit. Id diam maecenas ultricies mi eget. Orci a scelerisque purus semper eget duis at tellus at. Ipsum a arcu cursus vitae congue mauris. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Interdum varius sit amet mattis vulputate enim.

                A diam sollicitudin tempor id eu nisl nunc mi ipsum. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Cursus risus at ultrices mi tempus imperdiet nulla. Semper viverra nam libero justo laoreet sit. Sit amet massa vitae tortor condimentum lacinia quis. Eu scelerisque felis imperdiet proin. Placerat vestibulum lectus mauris ultrices. Urna id volutpat lacus laoreet non. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Non arcu risus quis varius quam quisque id diam. Aliquam malesuada bibendum arcu vitae elementum curabitur. Nam at lectus urna duis convallis convallis tellus. Malesuada proin libero nunc consequat interdum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.

                Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Sit amet cursus sit amet. Arcu bibendum at varius vel pharetra vel turpis nunc. Amet est placerat in egestas. Sed viverra tellus in hac habitasse platea. Lobortis elementum nibh tellus molestie nunc non blandit massa. Ornare arcu dui vivamus arcu felis bibendum. Tristique senectus et netus et malesuada fames ac. Mi sit amet mauris commodo quis. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis. Eget velit aliquet sagittis id consectetur.

                Gravida rutrum quisque non tellus orci ac auctor augue mauris. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Nascetur ridiculus mus mauris vitae ultricies leo integer. In hac habitasse platea dictumst. Volutpat lacus laoreet non curabitur gravida arcu ac. Auctor urna nunc id cursus. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Dui faucibus in ornare quam viverra orci sagittis eu. Velit dignissim sodales ut eu. At auctor urna nunc id cursus metus aliquam. Fermentum dui faucibus in ornare quam viverra. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Urna nunc id cursus metus. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Risus viverra adipiscing at in. Venenatis tellus in metus vulputate eu.

                Vulputate ut pharetra sit amet aliquam id. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Convallis a cras semper auctor neque vitae tempus quam. Morbi quis commodo odio aenean sed. Placerat duis ultricies lacus sed turpis. Elit pellentesque habitant morbi tristique. Lectus sit amet est placerat in. Laoreet id donec ultrices tincidunt. Mi quis hendrerit dolor magna eget est lorem. Libero enim sed faucibus turpis in. Risus viverra adipiscing at in tellus integer feugiat. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique.

                Enim nunc faucibus a pellentesque sit. Sed velit dignissim sodales ut eu sem integer vitae justo. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Elementum eu facilisis sed odio morbi quis commodo odio. Maecenas accumsan lacus vel facilisis volutpat est velit. Augue mauris augue neque gravida in. Justo laoreet sit amet cursus sit amet dictum sit amet. Magnis dis parturient montes nascetur ridiculus mus mauris. A lacus vestibulum sed arcu non odio euismod lacinia at. Magna ac placerat vestibulum lectus mauris ultrices eros in. Pharetra sit amet aliquam id. Nisi porta lorem mollis aliquam ut porttitor leo a diam. Felis eget velit aliquet sagittis id consectetur purus ut. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Proin libero nunc consequat interdum varius sit. Vulputate enim nulla aliquet porttitor. Quis blandit turpis cursus in hac habitasse platea dictumst. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Sit amet risus nullam eget felis.

                Orci sagittis eu volutpat odio facilisis. Orci ac auctor augue mauris augue neque gravida in. Sit amet nulla facilisi morbi tempus iaculis urna. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Ac tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Mattis nunc sed blandit libero volutpat. Magna etiam tempor orci eu. Accumsan in nisl nisi scelerisque eu. Sit amet justo donec enim diam vulputate ut pharetra. Dolor morbi non arcu risus quis varius. Amet dictum sit amet justo donec enim diam vulputate. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Lacus vel facilisis volutpat est velit. Duis ut diam quam nulla porttitor massa id neque. Tristique senectus et netus et malesuada fames ac. Nisl vel pretium lectus quam id leo in vitae.

                Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Ipsum nunc aliquet bibendum enim. Sit amet facilisis magna etiam tempor orci eu. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Cursus turpis massa tincidunt dui ut ornare lectus sit. Vel eros donec ac odio tempor orci dapibus ultrices in. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Consectetur purus ut faucibus pulvinar elementum integer enim. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Tincidunt praesent semper feugiat nibh. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Pellentesque habitant morbi tristique senectus et netus et malesuada.

                Risus quis varius quam quisque id diam vel. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Non consectetur a erat nam at lectus urna. Risus commodo viverra maecenas accumsan lacus vel. Vulputate eu scelerisque felis imperdiet proin. Libero id faucibus nisl tincidunt eget nullam non. Sed risus pretium quam vulputate. Viverra nam libero justo laoreet sit amet cursus sit. Etiam sit amet nisl purus in mollis nunc sed id. Volutpat odio facilisis mauris sit amet massa vitae.

                Aliquam nulla facilisi cras fermentum odio eu. Aliquam etiam erat velit scelerisque. Donec enim diam vulputate ut pharetra sit. Faucibus pulvinar elementum integer enim neque. Nisl pretium fusce id velit ut tortor pretium. Massa tincidunt dui ut ornare. Senectus et netus et malesuada fames ac turpis egestas. Fames ac turpis egestas sed tempus urna et pharetra pharetra. Convallis posuere morbi leo urna molestie at elementum eu. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Tortor posuere ac ut consequat semper viverra nam libero justo. Et odio pellentesque diam volutpat commodo sed egestas. Ac orci phasellus egestas tellus rutrum. Sem et tortor consequat id porta. Ultrices dui sapien eget mi proin sed libero enim sed. Commodo odio aenean sed adipiscing diam donec adipiscing.

                Faucibus nisl tincidunt eget nullam. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Tempus imperdiet nulla malesuada pellentesque elit. Semper risus in hendrerit gravida rutrum quisque non tellus. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. In ante metus dictum at tempor commodo ullamcorper. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Ut venenatis tellus in metus vulputate eu. Varius vel pharetra vel turpis nunc eget. Neque volutpat ac tincidunt vitae.

                Sed vulputate mi sit amet mauris. Auctor augue mauris augue neque gravida in fermentum. Morbi tempus iaculis urna id. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Massa enim nec dui nunc mattis enim ut tellus. Sit amet nisl purus in. Nisi lacus sed viverra tellus in hac. Ornare arcu odio ut sem nulla pharetra. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Ultricies mi quis hendrerit dolor magna eget est lorem ipsum. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales.

                Nam at lectus urna duis convallis. Sed vulputate odio ut enim. Lorem donec massa sapien faucibus. Tincidunt augue interdum velit euismod in pellentesque massa. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Tristique et egestas quis ipsum suspendisse ultrices gravida. Auctor neque vitae tempus quam pellentesque. Scelerisque felis imperdiet proin fermentum. Maecenas ultricies mi eget mauris pharetra et. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Orci ac auctor augue mauris augue neque gravida. Risus ultricies tristique nulla aliquet enim tortor at. Facilisis magna etiam tempor orci eu lobortis elementum nibh tellus. Nulla facilisi etiam dignissim diam quis enim lobortis. Facilisi nullam vehicula ipsum a arcu cursus vitae. Sit amet aliquam id diam maecenas ultricies mi. Sit amet consectetur adipiscing elit duis. Mi eget mauris pharetra et ultrices. Pellentesque id nibh tortor id aliquet. Aliquet eget sit amet tellus cras adipiscing enim eu turpis.

                Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Tristique senectus et netus et. Non enim praesent elementum facilisis leo vel fringilla est. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Sapien nec sagittis aliquam malesuada bibendum arcu. Dui vivamus arcu felis bibendum ut tristique et. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Condimentum lacinia quis vel eros donec ac odio tempor orci. Interdum posuere lorem ipsum dolor. Massa tincidunt dui ut ornare lectus sit. Arcu dui vivamus arcu felis bibendum. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Dui vivamus arcu felis bibendum ut tristique et. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Volutpat diam ut venenatis tellus. Et malesuada fames ac turpis egestas integer. Arcu odio ut sem nulla pharetra diam sit.

                Venenatis urna cursus eget nunc scelerisque viverra mauris in. A diam maecenas sed enim ut sem viverra aliquet. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Metus dictum at tempor commodo ullamcorper. Neque laoreet suspendisse interdum consectetur libero id. Rhoncus est pellentesque elit ullamcorper dignissim cras. Amet nulla facilisi morbi tempus iaculis urna id. Diam phasellus vestibulum lorem sed risus ultricies tristique. Velit sed ullamcorper morbi tincidunt. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur.

                Sed velit dignissim sodales ut eu sem. Neque egestas congue quisque egestas diam in arcu cursus euismod. Dignissim cras tincidunt lobortis feugiat vivamus. Mi proin sed libero enim sed faucibus. Sit amet justo donec enim diam vulputate ut pharetra sit. Ut tristique et egestas quis ipsum suspendisse. Purus viverra accumsan in nisl nisi. Turpis egestas integer eget aliquet nibh. Viverra vitae congue eu consequat ac felis donec. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Turpis nunc eget lorem dolor sed viverra ipsum. Odio pellentesque diam volutpat commodo sed.

                Quis lectus nulla at volutpat diam. Aliquam ultrices sagittis orci a scelerisque. Ipsum dolor sit amet consectetur adipiscing elit duis. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor magna. Tellus id interdum velit laoreet id donec ultrices. Eu sem integer vitae justo eget magna. Massa tincidunt nunc pulvinar sapien. Fringilla ut morbi tincidunt augue. Nulla at volutpat diam ut venenatis. Elit sed vulputate mi sit amet mauris. Lectus proin nibh nisl condimentum id venenatis a. Dignissim convallis aenean et tortor at risus viverra adipiscing. Sit amet porttitor eget dolor morbi non. Nisl condimentum id venenatis a. Tempus egestas sed sed risus pretium quam. Id porta nibh venenatis cras sed.

                Quam id leo in vitae turpis massa sed elementum. Lobortis feugiat vivamus at augue eget. Aliquet sagittis id consectetur purus ut faucibus. Ante in nibh mauris cursus mattis molestie. Tincidunt lobortis feugiat vivamus at. Lectus quam id leo in vitae turpis massa. In mollis nunc sed id semper risus in. Urna cursus eget nunc scelerisque viverra mauris. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Scelerisque varius morbi enim nunc faucibus. Purus non enim praesent elementum facilisis leo vel fringilla est. Ut etiam sit amet nisl purus in. Mollis aliquam ut porttitor leo a. Posuere urna nec tincidunt praesent semper. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Sit amet mattis vulputate enim nulla aliquet porttitor. Tortor condimentum lacinia quis vel eros donec.

                Nunc aliquet bibendum enim facilisis gravida. Risus commodo viverra maecenas accumsan lacus. Tellus orci ac auctor augue. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Eget nullam non nisi est. Vitae congue eu consequat ac felis donec et. Arcu cursus euismod quis viverra. Ante in nibh mauris cursus mattis molestie. Eu turpis egestas pretium aenean pharetra magna. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Pretium aenean pharetra magna ac placerat vestibulum. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Leo vel orci porta non pulvinar neque. Ullamcorper a lacus vestibulum sed. Urna neque viverra justo nec ultrices. Euismod quis viverra nibh cras. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Ut aliquam purus sit amet. Vel risus commodo viverra maecenas.</p>
        </div>

    )
}

export default BlogPage